### ISSUE TITLE
Node red does not start if the RFID reader is not connected

### ISSUE THREAD

**Issue by pato-loco** [LennartHennigs/node-red-contrib-rc522#1]
I have placed and deployed the node RC522 in an active flow. When the RFID reader is connected to the Raspberry Pi an is online, Node-Red starts. If the reader is not connected or goes off during operation (failure, poweroff, ...), Node-Red does not start or crashes. Reboot does not fix it. 
The log file will then show, for example, that the connection to the MQTT-Broker was interrupted and that the web socket is not running.

My System: Raspbian Buster with Raspi 3B+

**Comment by pato-loco** [comment]
no support here?

**Comment by LennartHennigs** [comment]
Hello,
as this is my first node red node I am by no means an expert but I will look into it. 
But this might take a couple of days.
Cheers
l.

**Comment by LennartHennigs** [comment]
Hi, give the latest commit a try. It works on my side.

**Comment by pato-loco** [comment]
It works! Thank ya!
