### ISSUE TITLE
Read out Iso 14443-4 cards

### ISSUE THREAD

**Issue by MasterOfPuppets111** [LennartHennigs/node-red-contrib-rc522#3]
It is possible to read out RFID Cards with the Iso 14443-4 Standart? I dont get a reading =( with iso 14443-3 cards it works fine.

**Comment by LennartHennigs** [comment]
By looking at the dataset of the [rc522](https://www.nxp.com/docs/en/data-sheet/MFRC522.pdf) and the [ISO Standard](https://en.wikipedia.org/wiki/ISO/IEC_14443) I think no. 

It says that the RC522 supports  type A cards. I guess yours is a type B card. 

Plus, this is only a Node-Red wrapper for [this nodejs library](https://github.com/miguelbalboa/rfid). The author might be able to give you a better answer.
