### ISSUE TITLE
Reading tags with 0

### ISSUE THREAD

**Issue by Zaurik97** [LennartHennigs/node-red-contrib-rc522#6]
Hi,
I noticed that if a tag contains a 0 like this "ED 5A 9B 03", the node returns "ed5a9b3", is there a way to fix this?

thanks for helping.

**Comment by LennartHennigs** [comment]
Hey, 
please check out this version:
https://github.com/LennartHennigs/node-red-contrib-rc522/pull/7

This should return two-digit UID parts.
I did not test it, as I didn't have an up-to-date version of NodeRed installed. 
Trying to install it plus my lib threw a few errors.

**Comment by Zaurik97** [comment]
Thanks!
it's working.
